
namespace: development

replicaCount: 1

image:
  repository: mubinahmed/user-management
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080


ingress:
  enabled: true
  host: user-management.local
