apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: development
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==
  SPRING_DATASOURCE_PASSWORD: ZGV2
  SPRING_DATASOURCE_URL: amRiYzpteXNxbDovL215c3FsLXNlcnZpY2UuZGF0YWJhc2Uuc3ZjLmNsdXN0ZXIubG9jYWw6MzMwNi9jaGFsbGVuZ2U/Y3JlYXRlRGF0YWJhc2VJZk5vdEV4aXN0PXRydWUmYXV0b1JlY29ubmVjdD10cnVl
  SPRING_DATASOURCE_WRITER_URL: amRiYzpteXNxbDovL215c3FsLXNlcnZpY2UuZGF0YWJhc2Uuc3ZjLmNsdXN0ZXIubG9jYWw6MzMwNi9jaGFsbGVuZ2U/Y3JlYXRlRGF0YWJhc2VJZk5vdEV4aXN0PXRydWUmYXV0b1JlY29ubmVjdD10cnVl


### Note: I am adding this just for code challenge purpose, otherwise secrets should not be stored in github, secrets should be encrypted and kept in aws secrets management or vault like: hasicorp vault, github actions screts
