apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: database
spec:
  capacity:
    storage: 1Gi  # The size of the volume should match the actual size of the EBS volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Allow a single node to read/write
  persistentVolumeReclaimPolicy: Retain  # Keep the volume after PVC deletion
  storageClassName: ebs-sc  # This should match your PVC's StorageClass if applicable
  awsElasticBlockStore:
    volumeID: vol-0d122e4b3ca595a4a  # The EBS volume ID you want to use
#    fsType: ext4  # or xfs, depending on the filesystem type of your volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc           # Name of the PVC, used for referencing in your applications
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce         # Specifies that the volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 1Gi          # Specifies the amount of storage requested (1Gi in this case)
  storageClassName: ebs-sc  # The name of the StorageClass; must match the PV’s storageClassName


